apiVersion: v1
kind: Pod
metadata:
  name: javaweb
spec:
  templates:
    metadata:
      labels:
        app:javaweb
spec:
  containers:
  - image: docker.io/chetant/restappone
    name: war
    volumeMounts:
    - mountPath: /app
      name: app-volume
  - image: tomcat
    name: javaweb
    command: [ "/usr/local/tomcat/bin/startup.sh", "run"]
    volumeMounts:
    - mountPath: /usr/local/tomcat/webapps
      name: app-volume
    ports:
    - containerPort: 8080
      hostPort: 8080
  volumes:
  - name: app-volume
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: restuiapi
spec:
  templates:
    metadata:
      labels:
        app:restuiapi
spec:
  containers:
  - image: docker.io/chetant/restappone
    name: war
    volumeMounts:
    - mountPath: /app
      name: app-volume
  - image: tomcat
    name: restuiapi
    command: [ "/usr/local/tomcat/bin/startup.sh", "run"]
    volumeMounts:
    - mountPath: /usr/local/tomcat/webapps
      name: app-volume
    ports:
    - containerPort: 8181
      hostPort: 8181
  volumes:
  - name: app-volume
---
kind: Service
apiVersion: v1
metadata:
  name: javaweb
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    name: javaweb
---
kind: Service
apiVersion: v1
metadata:
  name: restuiapi
spec:
  type: LoadBalancer
  ports:
    - port: 8181
  selector:
    name: restuiapi
