apiVersion: v1
kind: Pod
metadata:
  name: restappui
spec:
  templates:
    metadata:
      labels:
        app:restappui
spec:
  containers:
  - image: docker.io/chetant/restappuiimage
    name: war
    volumeMounts:
    - mountPath: /app
      name: app-volume
  - image: tomcat
    name: restappui
    command: [ "/usr/local/tomcat/bin/startup.sh", "run"]
    volumeMounts:
    - mountPath: /usr/local/tomcat/webapps
      name: app-volume
    ports:
    - containerPort: 8080
      hostPort: 8080
  - image: k8s.gcr.io/liveness
    name: liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /RestFrameNewApp/feature
        port: 8080
        httpHeaders:
        - name: X-Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
  volumes:
  - name: app-volume
    emptyDir: {}
